version: "3.5"
services:
  orders-api:
    build: ./api/.
    command: sh -c "npm install && npm start"
    ports:
      - target: 3000
        published: 3000
    networks:
      - counter-net
    working_dir: /src
    volumes:
      - c:/docker_shared/orders_app/api:/src

  orders-db:
    build: ./db/.
    command: sh -c "npm install && npm start"
    networks:
      - counter-net
    working_dir: /src
    volumes:
      - c:/docker_shared/orders_app/db:/src

  redis:
    image: "redis:alpine"
    networks:
      counter-net:

networks:
  counter-net:
