version: "3.5"
services:
  orders-api:
    build: ./api/.
    command: sh -c "npm install && npm start"
    ports:
      - target: 3000
        published: 3000
    networks:
      - counter-net
    working_dir: /src
    volumes:
      - c:/docker_shared/orders_app/api:/src

  orders-db:
    build: ./db/.
    command: sh -c "npm install && npm start"
    networks:
      - counter-net
    working_dir: /src
    volumes:
      - c:/docker_shared/orders_app/db:/src

  redis:
    image: "redis:alpine"
    networks:
      counter-net:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      counter-net:

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      counter-net:

networks:
  counter-net:
